# -*- coding: utf-8 -*-
"""
/***************************************************************************
 bdaoi
                                 A QGIS plugin
 bdaoi
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-17
        copyright            : (C) 2023 by srmaper
        email                : 1139949042
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load bdaoi class from file bdaoi.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .bdaoi import bdaoi
    return bdaoi(iface)
